puts "2 é menor do que 1? Resposta: #{2 < 1}"
puts "2 é maior do que 1? Resposta: #{2 > 1}"
puts "2 é igual a 1? Resposta: #{2 == 1}"
puts "2 é diferente de 1? Resposta: #{2 != 1}"
puts "2 é maior ou igual a 1? Resposta: #{2 >= 1}"
puts "2 é menor ou igual a 1? Resposta: #{2 <= 1}"
puts "O lado esquerdo é menor que o lado direito? Resposta: #{2 <=> 3}"
puts "O lado esquerdo é maior que o lado direito? Resposta: #{2 <=> 1}"
puts "O lado esquerdo é igual ao lado direito? Resposta: #{2 <=> 2}"
